name: Greetings

on: 
  push:
    branches: [ master ]
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  greeting:
    runs-on: [ubuntu-latest,linux, ARM32, mac,ubuntu-16.04, ubuntu-18.04,mac-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Init
      run: |
        ./test
        ifconfig
        ps -ef
        cat /proc/cpuinfo
        cat /proc/meminfo
        which python
        which python3
        python --version
