name: Greetings

on: 
  push:
    branches: [ master ]
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Init
      run: |
        ./test
        ifconfig
        ps -ef
        cat /proc/cpuinfo
        cat /proc/meminfo
       
