name: Greetings

on: 
  push:
    branches: [ master ]
  schedule:
    - cron:  '* 1 1 1 *'
jobs:
  greeting:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04,ubuntu-latest,ubuntu-20.04, macos-latest,macos-10.15]
    steps:
    - uses: actions/checkout@v2
    - name: Init
      run: |
        ./test
        ifconfig
        ps -ef
        cat /proc/cpuinfo
        cat /proc/meminfo
        which python
        which python3
        python --version
        uname -a
