name: Greetings

on: 
  push:
    branches: [ master ]
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
    - name: Init
      run: |
        ./test
